### ISSUE TITLE
Add usage to readme

### ISSUE THREAD

**Issue by coltenkrauter** [gforcada/ansible-compile-python#15]
Hi there, I am new to ansible. I would love to take advantage of what you've got here, but I don't know how to add it to my ansible playbook.

It would be great if you had info about how to use your playbook or how to add it to my playbook.

Thanks!

**Comment by gforcada** [comment]
@coltenkrauter thanks for the issue, indeed, some generic guidelines/instructions would be a good idea, but maybe even better would be to link to the official docs where it explains that, which probably would be way better than what I could write here :sweat_smile:

**Comment by gforcada** [comment]
Seems that meanwhile some information is already on the `README` if you still think there is room for improvement, please ask up :)
