### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by tcinbis** [gforcada/ansible-compile-python#18]
Hey @gforcada ,

thanks for this role! Before I start using it I wanted to ask, whether it is still maintained/used by you, because I saw that some of the more recent python versions are missing right now?

Maybe this is on purpose and I am just not seeing why. Let me know, what you think and I am happy to also contribute here if it is still maintained.

Thanks in advance!

**Comment by franck-charles** [comment]
Hi,
This role is not used by me.
Thanks 
Franck

**Comment by gforcada** [comment]
Hi @tcinbis ! Yes, it is somehow still maintained :) just vacations and coronavirus got in between though.

Adding support for new versions is trivial, I will update them now, but anytime I miss a new release, please feel free to create a merge request and send friendly pings if I miss to merge it! :sparkles:

**Comment by tcinbis** [comment]
Awesome! Thanks for letting me know! :)

**Comment by gforcada** [comment]
Just pushed a commit with all new versions, in a few minutes I will make a release!

**Comment by gforcada** [comment]
2.6.7 is out on galaxy.ansible.com :)
